parameters:
#    avkdev_ym_parser.example.class: Avkdev\YmParserBundle\Example

services:
#    avkdev_ym_parser.example:
#        class: %avkdev_ym_parser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    avkdev_ym_parser.task_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Avkdev\YmParserBundle\Entity\Task

    avkdev_ym_parser.product_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Avkdev\YmParserBundle\Entity\Product

    avkdev_ym_parser.ymparser:
        class: Avkdev\YmParserBundle\Parser\YandexMarket
        calls:
            - [ setContainer,[ @service_container ] ]