<?php

namespace Avkdev\YmParserBundle\Entity;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findByYandexModelId(array $ids)
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->in('yandexModelId', $ids));
        return $this->matching($criteria);
    }
}
